export const CONFIG_ELEMENT = {
  LOG_LEVEL: 'server:logLevel',
  PORT: 'server:port',
  OIDC_JWKS_URL: 'oidc:jwksUrl',
  JSON_BODY_LIMIT: 'server.bodyLimit',
  MORGAN_FORMAT: 'server:morganFormat',
  CDOGS_TOKEN_ENDPOINT: 'cdogs:tokenEndpoint',
  CDOGS_BASE_URL: 'cdogs:baseUrl',
  CDOGS_CLIENT_ID: 'cdogs:clientID',
  CDOGS_CLIENT_SECRET: 'cdogs:clientSecret',
  ENVIRONMENT: 'environment',
  REDIS_PORT: 'redis:port',
  REDIS_HOST: 'redis:host',
  NATS_URL: 'messaging:natsUrl',
};
