---
apiVersion: v1
kind: Template
labels:
  template: pen-report-generation-pipeline
metadata:
  name: pen-report-generation-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "pen-report-generation-pipeline"
  spec:
    source:
      git:
        uri: "https://github.com/bcgov/EDUC-PEN-REPORT-GENERATION-API"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/Jenkinsfile
