# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: API CI

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths:
      - 'api/src/**'
      - 'api/tests/unit/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/src/**'
      - 'api/tests/unit/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run lint
    #- run: npm run test:unit
      #env:
        #NODE_ENV: 'test'
